Connected Applications to Backend
WilliamRagstad/IV1201-Project pull request #38
Opened 2022-02-18 14:32 UTC by Willgar

2022-02-21 13:01 UTC, WilliamRagstad requested changes

2022-02-21 13:01 UTC, WilliamRagstad commented on run.bat
> +start cmd /k "aleph dev recruitment-app --allow-net"
What part of the app needs access to networking?

2022-02-21 13:10 UTC, WilliamRagstad requested changes

2022-02-21 13:10 UTC, WilliamRagstad commented on recruitment-api/model/Application.ts
> +    email: string;
Can be combined into a `user: User;` field

2022-02-21 15:38 UTC, WilliamRagstad commented on recruitment-api/repository/ApplicationRepository.ts
> +	}
This has now been fixed by @Luddeeeeeee. Use field names.

2022-02-22 09:55 UTC, Willgar commented on recruitment-api/controller/ApplicationController.ts
> +}
Due to Heroku Postgres limititations it can't be combined before with more separated SQL statements. Code is refactored now however to be more readable.

2022-02-22 10:38 UTC, Willgar commented on run.bat
> +start cmd /k "aleph dev recruitment-app --allow-net"
It was required for fetching API data.

2022-02-22 11:54 UTC, merged