Authorization and authentication
WilliamRagstad/IV1201-Project pull request #53
Opened 2022-03-03 13:22 UTC by Willgar

The API generates a JWT for the user when they login, which is stored locally with an expiry of 30 minutes. Client verifies JWT with API when generating pages for better authorization/authentication. 

Solves #42 

Minor issues: Change some requests to POST instead of GET ( Difficulty with Knight ),
Formatting,

2022-03-03 14:42 UTC, WilliamRagstad requested changes

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-api/service/UserService.ts
> +    return 0;
Varför returnera `0` istället för `false`?

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-api/controller/UserController.ts
> +      notFound(response);
Här så skulle userExists kunna vara `boolean | Role`, vilket skulle kunna snygga upp if-satserna.

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-api/service/UserService.ts
> +    return 0;
På rad 53 så kan vi till och med returnera `user.role ?? false`.

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/lib/verification.ts
> +export const useVerify = () => {
Borde inte heta `useVerify` utan något mer kopplat till det den faktiskt gör. Sen behöver vi inte göra det här på klienten, går mycket snabbare att göra allt på servern.

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/components/header.tsx
> +        {(title!=="other") && (<><a href="/" onClick={()=>{localStorage.clear();window.location.href="/";}}>Logout</a></>)}
Slå ihop varje fall, kanske en switch vore bra här? där default fallet är other.

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/pages/application.tsx
> +      (title!="recruiter") && (<><p>Error 403 - Forbidden</p></>) ||
401 istället?

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/pages/job.tsx
> +      {(title!=="applicant")&&(<><p>403 - Forbidden Access</p></>) ||
Forbidden Access eller Forbidden som i förra filen?
Tycker vi använder `401 Unauthorized` istället.

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/pages/job.tsx
> +      {(title!=="applicant")&&(<><p>403 - Forbidden Access</p></>) ||
Samma här, slå ihop båda fallen

2022-03-03 14:42 UTC, WilliamRagstad commented on recruitment-app/pages/login.tsx
> +    await fetch("http://localhost:8000/user/validate/"+data.get("email")+"/"+data.get("password"))
Varför inte använda `password` istället för det som görs på rad 23-26?
Lägg till ett `id` attribut på email också:
```html
<input type="email" name="email" />
```

2022-03-03 14:42 UTC, WilliamRagstad commented on shared/jwt.ts
> +}
Behöver den ligga i shared?
Appen använder den inte och kommer nog aldrig göra det.

2022-03-04 07:49 UTC, Willgar commented on recruitment-api/service/UserService.ts
> +    return 0;
Tänkte att det skulle se skumt ut med number | boolean istället för bara number, men ändrar det nu(samt ändrar lite hur JWT payloaden skapas).

2022-03-04 07:50 UTC, Willgar commented on recruitment-api/controller/UserController.ts
> +      notFound(response);
Ändrat hur jwt payloaden hanteras, borde vara bättre nu

2022-03-04 07:51 UTC, Willgar commented on recruitment-app/lib/verification.ts
> +export const useVerify = () => {
Bytt namn, men själva verifieringen sker på servern, det här är bara för att få servern att verifiera.

2022-03-04 07:52 UTC, Willgar commented on recruitment-app/pages/application.tsx
> +      (title!="recruiter") && (<><p>Error 403 - Forbidden</p></>) ||
Ja, blandade ihop dem.

2022-03-04 07:53 UTC, Willgar commented on recruitment-app/pages/login.tsx
> +    await fetch("http://localhost:8000/user/validate/"+data.get("email")+"/"+data.get("password"))
Det var preliminärt skapat för att bli en POST request vilket inte fungerade så jag behöll strukturen ifall man ville ändra på det senare.

2022-03-04 07:53 UTC, Willgar commented on shared/jwt.ts
> +}
Flyttad till api/lib

2022-03-04 08:08 UTC, Willgar commented on recruitment-app/components/header.tsx
> +        {(title!=="other") && (<><a href="/" onClick={()=>{localStorage.clear();window.location.href="/";}}>Logout</a></>)}
Lite mer ihopslaget, dock inge switch

2022-03-04 11:31 UTC, WilliamRagstad commented on recruitment-app/lib/verification.ts
> +export const fetchJWTAuthorization = () => {
Tycker något mer deskriptivt namn borde användas. Som `fetchUserTitle` till exempel.
Den här funktionen behöver verkligen inte ha **React** eller `useState`/`useEffect`.

Använd `async`/`await` istället.

2022-03-04 11:31 UTC, WilliamRagstad commented on recruitment-app/pages/login.tsx
> +        localStorage.setItem("JWT", data);
Borde vi spara den i en cookie istället? Nu sparas den på klienten men skickas aldrig tillbaka till servern, eller?

2022-03-05 23:33 UTC, WilliamRagstad commented
Nuvarande version är lite buggig

2022-03-08 13:15 UTC, merged